// <auto-generated />
namespace EntityFramework.APP.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class studentAddress : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(studentAddress));
        
        string IMigrationMetadata.Id
        {
            get { return "201707100334158_studentAddress"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
