// <auto-generated />
namespace EntityFramework.APP.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class FactGeo4 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FactGeo4));
        
        string IMigrationMetadata.Id
        {
            get { return "201707130203183_FactGeo4"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
